version: 2.1

executors:
  linux-node:
    docker:
      - image: cimg/node:lts
  linux-web:
    docker:
      # TODO: Remove in favor of `cimg/node:lts-browsers`?
      # See: https://circleci.com/developer/images/image/cimg/node#browsers
      - image: pyodide/pyodide-env:20221102-chrome107-firefox106

commands:
  emsdk-env:
    description: "emsdk_env.sh"
    steps:
      - run:
          name: emsdk_env.sh
          command: |
            # Prefer the default system-installed version of Node.js
            echo "NODE_JS = '$(which node)'" >> ./emsdk/.emscripten
            EMSDK_BASH=1 ./emsdk/emsdk construct_env >> $BASH_ENV
            echo 'export EMSDK_NUM_CORES=3' >> $BASH_ENV
            echo 'export EMCC_CORES=3' >> $BASH_ENV

jobs:
  install-emsdk:
    executor: linux-node
    steps:
      - checkout
      - run:
          name: install emsdk
          no_output_timeout: 1200
          command: |
            git clone https://github.com/emscripten-core/emsdk.git --depth=1
            cd emsdk
            ./emsdk install latest
            ./emsdk activate latest
      - persist_to_workspace:
          root: .
          paths:
            - emsdk

  build-libffi:
    executor: linux-node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: install automake
          command: |
            sudo apt-get update
            sudo apt-get install automake
      - emsdk-env
      - run: ./build.sh
      - run:
          name: build tests
          command: |
            cp -r testsuite/libffi.call testsuite/libffi.call.test
            cp -r testsuite/libffi.closures testsuite/libffi.closures.test
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.call.test
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.closures.test
      - persist_to_workspace:
          root: .
          paths:
            - target
            - testsuite

  build-libffi-bigint:
    executor: linux-node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: install automake
          command: |
            sudo apt-get update
            sudo apt-get install automake
      - emsdk-env
      - run: ./build.sh --enable-wasm-bigint
      - run:
          name: build tests
          command: |
            cp -r testsuite/libffi.call testsuite/libffi.call.test
            cp -r testsuite/libffi.closures testsuite/libffi.closures.test
            export EXTRA_LD_FLAGS="-s WASM_BIGINT"
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.call.test
            ./testsuite/emscripten-test-stuff/build-tests.sh testsuite/libffi.closures.test
      - persist_to_workspace:
          root: .
          paths:
            - target
            - testsuite

  test-firefox:
    executor: linux-web
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            git reset --hard
            mkdir test-results
            pytest --junitxml=test-results/junit.xml -k firefox testsuite/test_libffi.py
      - store_test_results:
          path: test-results

  test-chrome:
    executor: linux-web
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            git reset --hard
            pytest --junitxml=test-results/junit.xml -k chrome testsuite/test_libffi.py
      - store_test_results:
          path: test-results

  test-firefox-bigint:
    executor: linux-web
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            git reset --hard
            mkdir test-results
            pytest --junitxml=test-results/junit.xml -k firefox testsuite/test_libffi.py
      - store_test_results:
          path: test-results

  test-chrome-bigint:
    executor: linux-web
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            git reset --hard
            mkdir test-results
            pytest --junitxml=test-results/junit.xml -k chrome testsuite/test_libffi.py
      - store_test_results:
          path: test-results

  test-node:
    executor: linux-node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - emsdk-env
      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            testsuite/emscripten-test-stuff/node-tests.sh

  test-node-bigint:
    executor: linux-node
    steps:
      - checkout
      - attach_workspace:
          at: .
      - emsdk-env
      - run:
          name: run tests
          no_output_timeout: 1200
          command: |
            testsuite/emscripten-test-stuff/node-tests.sh --enable-wasm-bigint

workflows:
  version: 2
  build-and-test:
    jobs:
      - install-emsdk

      - build-libffi:
          requires:
            - install-emsdk
      - build-libffi-bigint:
          requires:
            - install-emsdk

      - test-firefox:
          requires:
            - build-libffi
      - test-chrome:
          requires:
            - build-libffi

      - test-firefox-bigint:
          requires:
            - build-libffi-bigint
      - test-chrome-bigint:
          requires:
            - build-libffi-bigint

      - test-node:
          requires:
            - install-emsdk
      - test-node-bigint:
          requires:
            - install-emsdk
